<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="examples\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="schemas\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="nlog.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
    <PackageReference Include="itext7" Version="9.5.0" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.4.0" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="SharpCompress" Version="0.44.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.1" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.22" />
  </ItemGroup>
</Project>
